server:
  port: 8080

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

rating-url: ${RATING_URL:http://localhost:8050}
library-url: ${LIBRARY_URL:http://localhost:8060}
reservation-url: ${RESERVATION_URL:http://localhost:8070}

# для CircuitBreakerConfig.defaults()
cb:
  sliding-window-size: 10
  minimum-number-of-calls: 2
  failure-rate-threshold: 50
  wait-duration-in-open-state-ms: 3000
  permitted-number-of-calls-in-half-open-state: 2